# docker-compose.yaml

version: '3.7'

services:
    my-backend:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 3000:3000
        env_file:
            - ./.env.docker

    my-database:
        image: mysql:latest
        environment:
            MYSQL_DATABASE: 'mydocker'
            MYSQL_ROOT_PASSWORD: '0000'
        ports:
            - 3301:3306
